Django/forum/forum/urls.py
from django.urls import path

from . import views

app_name = "forum"

urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.login, name="login"),
    path("addForum/", views.addForum, name="addForum"),
    path("showForum/", views.showForum, name="showForum"),
    path("logout/", views.logout, name="logout")
]

Django/forum/forum/views.py
from django.shortcuts import render
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse

from datetime import date, datetime

# there is problem with user session of "activeUser"

currentForum = []

class newUser(forms.Form):
    name = forms.CharField(label="name", min_length=3)

class newForum(forms.Form):
    comment = forms.CharField(label="comment", min_length=3)

# Create your views here.
def index(request):
    if "activeUser" not in request.session:
        # request.session["activeUser"] = ""
        return HttpResponseRedirect(reverse("forum:login"))
    else:
        return HttpResponseRedirect(reverse("forum:addForum"))

def login(request):
    # if "activeUser" not in request.session:

    if request.method == "POST":
        activeUser = newUser(request.POST)
        if activeUser.is_valid():
            userSession = activeUser.cleaned_data["name"]
            request.session['activeUser'] = userSession
            return HttpResponseRedirect(reverse("forum:showForum"))
        else:
            return render(request, "forum/login.html", {
                "message": "invalid input",
                "form": activeUser
            })
    else:
        # request.session["activeUser"] = False
        return render(request, "forum/login.html", {
            "message": "",
            "form": newUser()
        })
        
    # else:
    #     activeUser = request.session["activeUser"]
    #     return render(request, "forum/showForum.html", {
    #         "message": f"you have active session as {activeUser}",
    #         "form": currentForum
    #     })
    
def showForum(request):
    return render(request, "forum/showForum.html", {
        "forum": currentForum
    })
    
def addForum(request):
    if "activeUser" in request.session:
        if request.method == "POST":
            activeForm = newForum(request.POST)
            if activeForm.is_valid():
                activeName = request.session["activeUser"]
                activeComment = activeForm.cleaned_data["comment"]
                currentDate = datetime.now()
                currentTime = currentDate.strftime('%H:%M:%S')
                currentDate = date.today()
                currentForum.append({
                    "name": activeName,
                    "date": currentDate,
                    "time": currentTime,
                    "comment": activeComment
                })
                return HttpResponseRedirect(reverse("forum:showForum"))
            else:
                return render(request, "forum/addForum.html", {
                    "form": activeForm
                })
        else:
            return render(request, "forum/addForum.html", {
                "form": newForum()
            })
    else:
        # return render(request, "forum/login.html")
        return render(request, "forum/login.html", {
            "message": "You need to login first",
            "form": newUser()
        })
    
def logout(request):
    if "activeUser" in request.session:
        # del request.session["activeUser"]
        request.session.flush()
    return HttpResponseRedirect(reverse("forum:index"))

Django/forum/forum/templates/forum/addForum.html
{% extends "forum/layout.html" %}

{% block body %}
    <h2>Forum page</h2>
    <form action="{% url 'forum:addForum' %}" method="POST">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="upload">
    </form>
{% endblock %}

Django/forum/forum/templates/forum/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Forum App</title>
        <link href="{% static 'forum/style.css' %}" rel="stylesheet">

        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    </head>
    <body>
        <header>
            <h1>Forum</h1>
            <nav class="btn-group">
                <!-- <a href="">Index</a> -->
                <a href="{% url 'forum:login' %}">
                    <button type="button" class="btn btn-primary">Login</button>
                </a>
                <a href="{% url 'forum:addForum' %}">
                    <button type="button" class="btn btn-primary">Add Forum</button>
                </a>
                <a href="{% url 'forum:showForum' %}">
                    <button type="button" class="btn btn-primary">Show Forum</button>
                </a>
                <a href="{% url 'forum:logout' %}">
                    <button type="button" class="btn btn-primary">Logout</button>
                </a>
            </nav>
            <h2>
                {% if request.session.activeUser %}
                    {{ request.session.activeUser }}
                {% else %}
                    Username
                {% endif %}
            </h2>
        </header>
        <main>
            {% block body %}
            {% endblock %}
        </main>
    </body>
</html>

Django/forum/forum/templates/forum/login.html
{% extends 'forum/layout.html' %}

{% block body %}
    <h2>Login page</h2>
    <form action="{% url 'forum:login' %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="login">
    </form>
    {{ message }}
{% endblock %}

Django/forum/forum/templates/forum/showForum.html
{% extends "forum/layout.html" %}

{% block body %}
    <h2>Show Forum page</h2>
    <ul>
        {% for post in forum %}
            <li>
                <b><i>Username: {{post.name}}</i></b>
                <b>{{post.date}} {{post.time}}</b>
                <p>{{post.comment}}</p>
            </li>
        {% empty %}
            <h3>No post yet!</h3>
        {% endfor %}
    </ul>
    {{ message }}
{% endblock %}