Django/notes/notes/urls.py
from django.urls import path

from . import views

app_name = "notes"

urlpatterns = [
    path('', views.homepage, name="homepage"),
    path('addNotes/', views.addNotes, name="addNotes"),
    path('viewNotes/', views.viewNotes, name="viewNotes"),
    path('deleteNotes/<int:noteIndex>', views.deleteNotes, name="deleteNotes"),
    path('editNotes/<int:noteIndex>', views.editNotes, name="editNotes")
]

Django/notes/notes/models.py
from django.db import models

# Create your models here.
class Notes(models.Model):
    title = models.CharField(max_length=20)
    description = models.CharField(max_length=200)
    date = models.DateTimeField(auto_now=True)

Django/notes/notes/views.py
# from datetime import datetime, date

from django.shortcuts import render
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse

from .models import Notes

class notes(forms.Form):
    title = forms.CharField(label="Title", min_length=1, required=True)
    description = forms.CharField(label="Description", min_length=1, required=True)

# Create your views here.
def homepage(request):
    return render(request, 'notes/homepage.html')

def addNotes(request):
    if request.method == "POST":
        newNotes = notes(request.POST)
        if newNotes.is_valid():
            newTitle = newNotes.cleaned_data["title"]
            newDescription = newNotes.cleaned_data["description"]
            saveNote = Notes.objects.create(title=newTitle, description=newDescription)
            saveNote.save()
            return HttpResponseRedirect(reverse("notes:viewNotes"))
        else:
            return render(request, "notes/addNotes.html", {
                "form": newNotes
            })
    else:
        return render(request, "notes/addNotes.html", {
            "form": notes()
        })

def viewNotes(request):
    getNotes = Notes.objects.all()
    return render(request, "notes/viewNotes.html", {
        "notes": getNotes
    })

# def searchNotes(request):

def deleteNotes(request, noteIndex):
    getNote = Notes.objects.get(pk=noteIndex)
    getNote.delete()
    return HttpResponseRedirect(reverse("notes:viewNotes"))

def editNotes(request, noteIndex):
    getNote = Notes.objects.get(pk=noteIndex)
    if request.method == "POST":
        updatedNote = notes(request.POST)
        if updatedNote.is_valid():
            getNote.title = updatedNote.cleaned_data["title"]
            getNote.description = updatedNote.cleaned_data["description"]
            getNote.save()
            return HttpResponseRedirect(reverse("notes:viewNotes"))
        else:
            return render(request, "notes/editNotes.html", {
                "noteID": noteIndex,
                "note": updatedNote
            })
    else:
        return render(request, "notes/editNotes.html", {
            "noteID": noteIndex,
            # "note": notes(getNote)c
            "note": notes()
        })

Django/notes/notes/templates/notes/addNotes.html
{% extends 'notes/layout.html' %}

{% block body %}
    <h1>Add Notes Page</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="add notes">
    </form>
{% endblock %}

Django/notes/notes/templates/notes/editNotes.html
{% extends 'notes/layout.html' %}

{% block body %}
    <h2>Edit Note Page</h2>
    <form action="{% url 'notes:editNotes' noteID %}" method="POST">
        {% csrf_token %}
        {{ note }}
        <input type="submit" value="edit note">
    </form>
{% endblock %}

Django/notes/notes/templates/notes/homepage.html
{% extends 'notes/layout.html' %}

{% block body %}
    <h1>Notes App</h1>
    <h2>Welcome</h2>
{% endblock %}

Django/notes/notes/templates/notes/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Notes App</title>
        <link href="{% static 'notes/style.css' %}" rel="stylesheet">
    </head>
    <body>
        <nav>
            <a href="{% url 'notes:homepage' %}">Homepage</a>
            <a href="{% url 'notes:addNotes' %}">Add Notes</a>
            <a href="{% url 'notes:viewNotes' %}">View Notes</a>
        </nav>
        {% block body %}
        {% endblock %}
    </body>
</html>

Django/notes/notes/templates/notes/viewNotes.html
{% extends 'notes/layout.html' %}

{% block body %}
    <h1>Show Notes Page</h1>
    <ul>
        {% for note in notes %}
            <li>
                <h3>{{ note.title }}</h3>
                <h4>{{ note.date }}</h4>
                <p>{{ note.description }}</p>
                <br>
                <a href="{% url 'notes:deleteNotes' note.id %}">delete note</a>
                <a href="{% url 'notes:editNotes' note.id %}">edit note</a>
            </li>
        {% empty %}
            <h2>No notes found</h2>
        {% endfor %}
    </ul>
{% endblock %}