Django/todo1/app1/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('greet/<str:name>', views.greet, name="greet"),
    path('menus/', views.menus, name="menus")
]

Django/todo1/project6/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('app1/', include("app1.urls")),
    path('', include("todo.urls"))
]

Django/todo1/todo/urls.py
from django.urls import path

from . import views

app_name = "todo"

urlpatterns = [
    path('', views.index, name="index"),
    path('showTodo/', views.showTodo, name="showTodo"),
    path('addTodo/', views.addTodo, name="addTodo")
]

Django/todo1/app1/models.py
from django.db import models

# Create your models here.

Django/todo1/todo/models.py
from django.db import models

# Create your models here.

Django/todo1/app1/views.py
from django.shortcuts import render
from django.http import HttpResponse

menulist = [
    {
        "name": "spagety",
        "type": "food",
        "price": 12.00
    },
    {
        "name": "bread",
        "type": "food",
        "price": 8.00
    },
    {
        "name": "coffee",
        "type": "beverage",
        "price": 5.00
    },
    {
        "name": "sandwich",
        "type": "food",
        "price": 10.00
    }
]

# Create your views here.
def index(request):
    return HttpResponse("<h1>Welcome to app 1</h1>")

def greet(request, name):
    greeting = f"<h1>hello {name}</h1>"
    return HttpResponse(greeting)

def menus(request):
    return render(request, "app1/menus.html", {
        "menulist": menulist
    })

Django/todo1/todo/views.py
from django.shortcuts import render
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse

# defaultTodo = [
#     {
#         "name": "homework",
#         "description": "to hell with it"
#     },
#     {
#         "name": "learn django",
#         "description": "right away!"
#     },
#     {
#         "name": "read book",
#         "description": "what do I wanna read?"
#     }
# ]

class newTodo(forms.Form):
    todoName = forms.CharField(label="New Task")
    todoDescription = forms.CharField(label="New Task's description")

# Create your views here.
def index(request):
    return render(request, "todo/index.html")

def showTodo(request):
    if "todoList" not in request.session:
        request.session["todoList"] = []

    return render(request, "todo/showTodo.html", {
        "todolist": request.session["todoList"]
    })

def addTodo(request):
    if request.method == "POST":
        filledForm = newTodo(request.POST)
        if filledForm.is_valid():
            newTodoObject = {
                "name": filledForm.cleaned_data["todoName"],
                "description": filledForm.cleaned_data["todoDescription"]
            }
            request.session["todoList"] += [newTodoObject]
            return HttpResponseRedirect(reverse("todo:showTodo"))
        else:
            return render(request, "todo/addTodo.html", {
                "form": filledForm
            })

    return render(request, "todo/addTodo.html", {
        "form": newTodo()
    })

Django/todo1/app1/templates/app1/menus.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Menus</title>
        <link href="{% static 'app1/menu.css' %}" rel="stylesheet">
    </head>
    <body>
        <h1>Our menu</h1>
        <ul>
            {% for menu in menulist %}
                <li>
                    <h2>{{menu.name}}</h2>
                    <h3>{{menu.type}}</h3>
                    <h3>$ {{menu.price}}</h3>
                </li>
            {% endfor %}
        </ul>
    </body>
</html>

Django/todo1/todo/templates/todo/addTodo.html
{% extends 'todo/layout.html' %}

{% block body %}
    <!-- the action url: pay attention to it -->
    <form action="{% url 'todo:addTodo' %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>
{% endblock %}

Django/todo1/todo/templates/todo/index.html
{% extends 'todo/layout.html' %}

{% block body %}
    <p>index page</p>
{% endblock %}

Django/todo1/todo/templates/todo/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>To Do App</title>
        <link href="{% static 'todo/globalStyle.css' %}" rel="stylesheet">
    </head>
    <body>
        <h1>To Do App</h1>
        <nav>
            <a href="{% url 'todo:index' %}">Index</a>
            <a href="{% url 'todo:showTodo' %}">Todo List</a>
            <a href="{% url 'todo:addTodo' %}">Add Todo</a>
        </nav>
        {% block body %}
        {% endblock %}
    </body>
</html>

Django/todo1/todo/templates/todo/showTodo.html
{% extends 'todo/layout.html' %}

{% block body %}
    <ul>
        {% for todo in todolist %}
            <li>
                <h2>{{todo.name}}</h2>
                <p>{{todo.description}}</p>
            </li>
        {% empty %}
            <h2>No task yet</h2>
        {% endfor %}
    </ul>
{% endblock %}